### PR TITLE
Add Vietnamese translations

### PR DESCRIPTION
**Pull request by zeref-dragneel**
image
If the translation is already live and you want to make improvements (e.g. correct a typo,... ✏️), you can do so by simply editing the file and submitting a Pull Request 👍. It would be great if you can contribute your translations... 😉

### CODE REVIEW

**Comment by paulpacifico** [comment]
Hi!

Thanks you so much for this translation, it helps me so much!

I need to tweak the file a bit for make it fully compatible with Shutter but that should be done for the next release (v16.0).

Do you have a PayPal account to send you some money for your work? Please let me know on my mail: paulpacifico974@gmail.com

Thanks again,
Paul.

**Comment by zeref-dragneel** [comment]
> Do you have a PayPal account to send you some money for your work? Please let me know on my mail: [paulpacifico974@gmail.com](mailto:paulpacifico974@gmail.com)

Hi Paul,
Thank you very much, but I do it for free. You just need to upgrade the GUI for the app.

**Comment by paulpacifico** [comment]
That's so helpful! Thank your so much I'm very grateful of your translation.

Would you give me your full name (or a pseudo) to add it on the official website for the translation?

Paul.

**Comment by zeref-dragneel** [comment]
> That's so helpful! Thank your so much I'm very grateful of your translation.
> 
> Would you give me your full name (or a pseudo) to add it on the official website for the translation?
> 
> Paul.

Hi Paul,
My full name is Đặng Thành Đạt, You can call me Đạt.

**Pull request merged**
