### PR TITLE
Add arabic translation

### PR DESCRIPTION
**Pull request by ahmed-0011**
Hi, paul

This pull request adds the arabic translation. It was tested by replacing the content inside jp.properties with the unicode representation of the arabic translation. You probably need to apply the same logic to ar.properties as you did to jp.properties.

As you can see in the following screenshot, the left is the result of using ar.properties, and the right is the result of using jp.properties.

image

--

**I'm not sure if Shutter Encoder is built with consideration for RTL languages... Do you think it is possible to add RTL support for Arabic?**

### CODE REVIEW

**Review by paulpacifico — APPROVED** [review]

**Comment by paulpacifico** [comment]
Hi,
Thank you so much for your translation! It helps me a ton!

I just need to add edit the code to work like the japanese language otherwise everything seems perfect, good job!

Do you have a PayPal for sending a bit of money for your work?

Best,
Paul.

**Comment by paulpacifico** [comment]
I should be able to do RTL thanks to FlatLaf interface, I will try for the first time.

**Comment by ahmed-0011** [comment]
Thank you very much for your kind offer, but unfortunatly i don't have a PayPal account.

> I should be able to do RTL thanks to FlatLaf interface, I will try for the first time.

Good to hear that. I hope it will not be too complex and require too much rewriting to implement. 

I'm available if you need any guidance on how the RTL interface should look like.

**Comment by paulpacifico** [comment]
Do you have an other payment method to suggest?

It seems quite easy but I need to add a line for each component which is long.

I try to find a quicker way.
Paul.

**Comment by ahmed-0011** [comment]
Thanks, Paul, for the offer. But you really don't have to. I contributed to the project because I like Shutter Encoder, and witnessing it in Arabic would be enough for me :)

**Comment by paulpacifico** [comment]
🙏

**Pull request closed without merging**
