### PR TITLE
[translation] Spanish

### PR DESCRIPTION
**Pull request by sheykandi**
Added Spanish language
I am not familiar with GIT, so it is likely that I am not doing this well.
Thanks so much for such a piece of art! Very helpful!
Kandi

### CODE REVIEW

**Comment by paulpacifico** [comment]
Oh man, that's wonderful! You help me a lot thanks you so much!

I wanted to post on Shutter's reddit page to ask for German and Spanish translation, that's just a perfect timming!

Please contact me in private to: paulpacifico@free.fr
I need to speak with you about this.

Thanks again,
Paul.

**Comment by chenlung** [comment]
I wonder if we can use Transifex or similar. Might make it easier to maintain the translation strings?

**Comment by sheykandi** [comment]
Never heard of that. I'll do a little bit of research and I'll get back to you.Kandi

    On Friday, February 12, 2021, 4:45:01 PM EST, chenlung <notifications@github.com> wrote:  
 
 


I wonder if we can use Transifex or similar. Might make it easier to maintain the translation strings?

**Comment by sheykandi** [comment]
I am not familiar with any translation manager, but anything that could help translating is always welcome.
This is a complaint from a guy at alternativeto.net:
  Closed its code-base and spies on users with tracking.
  Clunky non-modifiable UI, with no interface wide navigation.
  Effectively takes projects hostage when it finds it opportune to require subscriptions.
  Deleted translations end up as suggestions for other strings.
  No gratis hosting for libre software that has source of revenue.
  Broken messaging system.
  Can only be used online, by people over 18 years old.
  Famously bad support, even for organizations that pay $200.000+ a year.

As an open-source alternative is Pootle (https://pootle.translatehouse.org/index.html). Reviews from alternativeto.net:
  - Very legit open source localization platform used by among others Evernote and SugarLabs.
  - From what I could see it has a nice user interface and the expected functionality. It's absolutely free, so for me it seems a good alternative.

**Pull request closed without merging**
