### PR TITLE
Add simplified Chinese translate under Languages folder/添加简体中文翻译

### PR DESCRIPTION
**Pull request by xBLACKICEx**
Add simplified Chinese translate under Languages folder/添加简体中文翻译,

I finished about 99% of the translation, and kept the rest in English, because these are all specialized words that I don't understand.

### CODE REVIEW

**Comment by paulpacifico** [comment]
Hi,

Thanks a lot for your work!
Someone else also sent me a Chinese translation this week, do you want to check it? 

Paul.

**Comment by xBLACKICEx** [comment]
> Hi,
> 
> Thanks a lot for your work!
> Someone else also sent me a Chinese translation this week, do you want to check it?
> 
> Paul.

Why not

**Comment by paulpacifico** [comment]
What is your OS? for send you the pre-release.

For info the Chinese language has to be translated to Unicode to be displayed into the UI.

**Comment by xBLACKICEx** [comment]
> What is your OS? for send you the pre-release.
> 
> For info the Chinese language has to be translated to Unicode to be displayed into the UI.

windows

**Comment by xBLACKICEx** [comment]
> What is your OS? for send you the pre-release.
> 
> For info the Chinese language has to be translated to Unicode to be displayed into the UI.
It's strange that vscode clearly shows utf-8.
image

**Comment by paulpacifico** [comment]
Yes but it doesn't display into the UI.

Here is the link to the BETA version: https://we.tl/t-xlBm0CeiEv

Warning, I did not tested this version, I'm currently developing it, it might have some bugs/issues.

**Comment by xBLACKICEx** [comment]
> Yes but it doesn't display into the UI.
> 
> Here is the link to the BETA version: https://we.tl/t-xlBm0CeiEv
> 
> Warning, I did not tested this version, I'm currently developing it, it might have some bugs/issues.

Well I tested most look like ok but have translation error. But for **Copy a tree**    **复制树** in Chinese is not the best translate, There is no such expression or phrase in Chinese. It would be better to “copy as the tree structure”（树状结构复制）
and theme setting
image
here he translates to (clear/清除(clean)) but need to be （亮色/light)

**Comment by paulpacifico** [comment]
Thank you so much! I will correct this before the release!

**Pull request closed without merging**
